<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRUD MVC</title>
</head>
<body>
    <header>
        <nav>
			<ul>
				<li>
		    		<a href="index.php">Accueil</a>
				</li>
                <li>
					<a href="index.php?route=create_user">Create</a>
				</li>
				<li>
					<a href="index.php?route=update_user">Update</a>
				</li>
			</ul>
		</nav>
    </header>
    <?php
        switch($route) {
        case "show_user":
            require "templates/users/show.phtml";
            break;
        case "create_user":
            require "templates/users/create.phtml";
            break;
        case "update_user":
            require "templates/users/update.phtml";
            break;
        default:
            require "templates/users/list.phtml";
            break;
        }
    ?>
</body>
</html>