<main>
	<h1>Créer un user</h1>

	<form action="index.php?route=check_create_user" method="post">
		<label for="nom">Nom :</label><br>
		<input type="text" id="last_name" name="last_name" required><br><br>

		<label for="prenom">Prénom :</label><br>
		<input type="text" id="first_name" name="first_name" required><br><br>

		<label for="email">Email :</label><br>
		<input type="email" id="email" name="email" required><br><br>

		<label for="motdepasse">Mot de passe :</label><br>
		<input type="password" id="password" name="password" required><br><br>

		<button type="submit">Créer l'utilisateur</button>
	</form>

</main>